/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import com.mysql.cj.jdbc.Driver;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JTextField;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author atesz
 */
public class AdminStaff extends javax.swing.JFrame {
    
    public long selected_staff;
    private Connection con;
    
    private Connection connect() {
        try {
            return DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital", "root", "Atoras21");
        } catch (SQLException ex) {
            ex.printStackTrace();
            return null;
        }
    }
    
    /**
     * Creates new form AdminStaff
     */
    public AdminStaff(long st_ıd) {
        this.selected_staff = st_ıd;
        //set_image(selected_staff);
        initComponents();
        con = connect();
        staff_info();
    }
    /*
    private void set_image(int selected_staff){
        String sex = null;
        try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital", "root", "Atoras21");
                String sql = "SELECT sex\n" +
                             "FROM staff\n" +
                             "WHERE Staff_ID = ?;";
                
            PreparedStatement pstmt = con.prepareStatement(sql);
            pstmt.setInt(1, selected_staff);
            
            ResultSet rs = pstmt.executeQuery();
            
            
            if (rs.next()) {
            sex = rs.getString("sex");
            // Check if sex is not null before comparing
            if (sex != null && sex.equals("m")) {
                ImageIcon image = new ImageIcon("indir.jpeg");
                this.admin_staff_image_label.setIcon(image);
            } else {
                ImageIcon image = new ImageIcon("a.jpeg");
                this.admin_staff_image_label.setIcon(image);
            }
        } else {
            // Handle the case when no data is found for the specified Staff_ID
            System.out.println("No data found for Staff_ID: " + selected_staff);
        }
            
            
        }
        catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        admin_staff_calendar_panel = new javax.swing.JPanel();
        admin_staff_calendar_9 = new javax.swing.JButton();
        admin_staff_calendar_10 = new javax.swing.JButton();
        admin_staff_calendar_11 = new javax.swing.JButton();
        admin_staff_calendar_13 = new javax.swing.JButton();
        admin_staff_calendar_14 = new javax.swing.JButton();
        admin_staff_calendar_15 = new javax.swing.JButton();
        admin_staff_calendar_16 = new javax.swing.JButton();
        admin_staff_calendar_17 = new javax.swing.JButton();
        admin_staff_image_panel = new javax.swing.JPanel();
        admin_staff_image_label = new javax.swing.JLabel();
        admin_staff_f_m_l_name_label = new javax.swing.JLabel();
        admin_staff_role_label = new javax.swing.JLabel();
        admin_staff_fire_button = new javax.swing.JButton();
        admin_staff_back_button = new javax.swing.JButton();
        admin_staff_salary_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        admin_staff_calendar_9.setText("09.00");

        admin_staff_calendar_10.setText("10.00");

        admin_staff_calendar_11.setText("11.00");

        admin_staff_calendar_13.setText("13.00");

        admin_staff_calendar_14.setText("14.00");

        admin_staff_calendar_15.setText("15.00");

        admin_staff_calendar_16.setText("16.00");

        admin_staff_calendar_17.setText("17.00");

        javax.swing.GroupLayout admin_staff_calendar_panelLayout = new javax.swing.GroupLayout(admin_staff_calendar_panel);
        admin_staff_calendar_panel.setLayout(admin_staff_calendar_panelLayout);
        admin_staff_calendar_panelLayout.setHorizontalGroup(
            admin_staff_calendar_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(admin_staff_calendar_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(admin_staff_calendar_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(admin_staff_calendar_9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(admin_staff_calendar_10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(admin_staff_calendar_11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(admin_staff_calendar_13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(admin_staff_calendar_14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(admin_staff_calendar_15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(admin_staff_calendar_16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(admin_staff_calendar_17, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
                .addContainerGap())
        );
        admin_staff_calendar_panelLayout.setVerticalGroup(
            admin_staff_calendar_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(admin_staff_calendar_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(admin_staff_calendar_9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(admin_staff_calendar_10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(admin_staff_calendar_11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(admin_staff_calendar_13, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(admin_staff_calendar_14, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(admin_staff_calendar_15, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(admin_staff_calendar_16, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(admin_staff_calendar_17, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout admin_staff_image_panelLayout = new javax.swing.GroupLayout(admin_staff_image_panel);
        admin_staff_image_panel.setLayout(admin_staff_image_panelLayout);
        admin_staff_image_panelLayout.setHorizontalGroup(
            admin_staff_image_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(admin_staff_image_panelLayout.createSequentialGroup()
                .addGroup(admin_staff_image_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(admin_staff_image_panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(admin_staff_image_label, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                    .addGroup(admin_staff_image_panelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(admin_staff_image_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(admin_staff_f_m_l_name_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(admin_staff_role_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        admin_staff_image_panelLayout.setVerticalGroup(
            admin_staff_image_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(admin_staff_image_panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(admin_staff_image_label, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(admin_staff_f_m_l_name_label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(admin_staff_role_label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        admin_staff_fire_button.setText("Fire");
        admin_staff_fire_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_staff_fire_buttonActionPerformed(evt);
            }
        });

        admin_staff_back_button.setText("Back");
        admin_staff_back_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_staff_back_buttonActionPerformed(evt);
            }
        });

        admin_staff_salary_label.setText("Salary :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(admin_staff_calendar_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(admin_staff_image_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(admin_staff_fire_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(admin_staff_back_button, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addComponent(admin_staff_salary_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(admin_staff_image_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(admin_staff_fire_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(admin_staff_back_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(admin_staff_salary_label, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(admin_staff_calendar_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void admin_staff_fire_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_staff_fire_buttonActionPerformed
        String url = "jdbc:mysql://localhost:3306/hospital";
        String username = "root";
        String password = "Atoras21";

        // ID of the row you want to delete
         // Replace 123 with the actual ID

        try (Connection conn = DriverManager.getConnection(url, username, password)) {
            // staff
            String sql = "DELETE FROM staff WHERE Staff_ID = ?";
            // Create a PreparedStatement with the SQL query
            PreparedStatement pstmt = conn.prepareStatement(sql);
            // Set the parameter for the ID of the row to delete
            pstmt.setLong(1, selected_staff);
            // Execute the delete operation
            int rowsDeleted = pstmt.executeUpdate();
            
            // family
            sql = "DELETE FROM family WHERE Family_ID = ?";
            // Create a PreparedStatement with the SQL query
            pstmt = conn.prepareStatement(sql);
            // Set the parameter for the ID of the row to delete
            pstmt.setLong(1, selected_staff);
            // Execute the delete operation
            int rowsDeleted2 = pstmt.executeUpdate();
            
            
            // address
            sql = "DELETE FROM address WHERE Address_ID = ?";
            // Create a PreparedStatement with the SQL query
            pstmt = conn.prepareStatement(sql);
            // Set the parameter for the ID of the row to delete
            pstmt.setLong(1, selected_staff);
            // Execute the delete operation
            int rowsDeleted3 = pstmt.executeUpdate();
            
            
            // Check if any rows were deleted
            if (rowsDeleted > 0) {
                this.setVisible(false);
                new Admin().setVisible(true);
            } else {
                System.out.println("No row found with the specified ID.");
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_admin_staff_fire_buttonActionPerformed

    private void admin_staff_back_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_staff_back_buttonActionPerformed
        new Admin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_admin_staff_back_buttonActionPerformed
    
        private void staff_info(){
            String f_ = "";
            String m_ = "";
            String l_ = "";
            String t_ = "";
            String final_s  = "";
            try {
                String sql = "SELECT F_name, M_name, L_name, Title FROM staff WHERE Staff_ID = ?";
                PreparedStatement pstmt = con.prepareStatement(sql);
                pstmt.setLong(1, selected_staff);
                ResultSet rs = pstmt.executeQuery();

                while (rs.next()) {
                    f_ = rs.getString("F_name");
                    m_ = rs.getString("M_name");
                    l_ = rs.getString("L_name");
                    t_ = rs.getString("Title");
                }

                final_s = f_ + " " + m_ + " " + l_;

                admin_staff_f_m_l_name_label.setText(final_s);
                admin_staff_role_label.setText(t_);

            } catch (SQLException ex) {
                ex.printStackTrace();
            }
        }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminStaff(0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admin_staff_back_button;
    private javax.swing.JButton admin_staff_calendar_10;
    private javax.swing.JButton admin_staff_calendar_11;
    private javax.swing.JButton admin_staff_calendar_13;
    private javax.swing.JButton admin_staff_calendar_14;
    private javax.swing.JButton admin_staff_calendar_15;
    private javax.swing.JButton admin_staff_calendar_16;
    private javax.swing.JButton admin_staff_calendar_17;
    private javax.swing.JButton admin_staff_calendar_9;
    private javax.swing.JPanel admin_staff_calendar_panel;
    private javax.swing.JLabel admin_staff_f_m_l_name_label;
    private javax.swing.JButton admin_staff_fire_button;
    private javax.swing.JLabel admin_staff_image_label;
    private javax.swing.JPanel admin_staff_image_panel;
    private javax.swing.JLabel admin_staff_role_label;
    private javax.swing.JLabel admin_staff_salary_label;
    // End of variables declaration//GEN-END:variables
}
