/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import com.mysql.cj.jdbc.Driver;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JTextField;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.DefaultListModel;
/**
 *
 * @author atesz
 */
public class Admin extends javax.swing.JFrame {
    
    private long _staff_id;
    
    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
        loadStaffDetails();
        loadPatientDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        admin_staff_scroll_pane = new javax.swing.JScrollPane();
        admin_staff_list = new javax.swing.JList<>();
        admin_see_staff_button = new javax.swing.JButton();
        admin_add_staff_button = new javax.swing.JButton();
        admin_patient_scroll_pane = new javax.swing.JScrollPane();
        admin_patient_list = new javax.swing.JList<>();
        admin_welcome_back_label = new javax.swing.JLabel();
        admin_add_medicine_button = new javax.swing.JButton();
        admin_update_staff_button = new javax.swing.JButton();
        admin_add_polyclinic_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        admin_staff_list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        admin_staff_scroll_pane.setViewportView(admin_staff_list);

        admin_see_staff_button.setText("See Staff");
        admin_see_staff_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_see_staff_buttonActionPerformed(evt);
            }
        });

        admin_add_staff_button.setText("Add Staff");
        admin_add_staff_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_add_staff_buttonActionPerformed(evt);
            }
        });

        admin_patient_list.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        admin_patient_scroll_pane.setViewportView(admin_patient_list);

        admin_welcome_back_label.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        admin_welcome_back_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        admin_welcome_back_label.setText("Welcome Back");

        admin_add_medicine_button.setText("Add Medicine");
        admin_add_medicine_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_add_medicine_buttonActionPerformed(evt);
            }
        });

        admin_update_staff_button.setText("Update Staff");
        admin_update_staff_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_update_staff_buttonActionPerformed(evt);
            }
        });

        admin_add_polyclinic_button.setText("Add Polyclinic");
        admin_add_polyclinic_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_add_polyclinic_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(admin_patient_scroll_pane, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(admin_add_polyclinic_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(admin_welcome_back_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(admin_add_medicine_button, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addComponent(admin_update_staff_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(admin_see_staff_button, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                        .addComponent(admin_staff_scroll_pane))
                    .addComponent(admin_add_staff_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(admin_staff_scroll_pane, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(admin_welcome_back_label, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(admin_add_medicine_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(admin_see_staff_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(admin_update_staff_button, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(admin_add_staff_button, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                            .addComponent(admin_add_polyclinic_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(admin_patient_scroll_pane))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void admin_add_medicine_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_add_medicine_buttonActionPerformed
        this.setVisible(false);
        new AdminAddMedicine().setVisible(true);
    }//GEN-LAST:event_admin_add_medicine_buttonActionPerformed

    private void admin_add_staff_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_add_staff_buttonActionPerformed
        this.setVisible(false);
        AdminAddStaff aas = new AdminAddStaff(0);
        aas.setVisible(true);
    }//GEN-LAST:event_admin_add_staff_buttonActionPerformed

    private void admin_add_polyclinic_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_add_polyclinic_buttonActionPerformed
        this.setVisible(false);
        new AdminAddPolyclinic().setVisible(true);
    }//GEN-LAST:event_admin_add_polyclinic_buttonActionPerformed

    private void admin_update_staff_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_update_staff_buttonActionPerformed
        this.setVisible(false);
        AdminAddStaff aas = new AdminAddStaff(1);
        aas.setVisible(true);
    }//GEN-LAST:event_admin_update_staff_buttonActionPerformed

    private void admin_see_staff_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_see_staff_buttonActionPerformed
        String[] info = admin_staff_list.getSelectedValue().split(" ");
        AdminStaff as = new AdminStaff(Long.parseLong(info[0]));
        if (info[0] != null) {
            this.setVisible(false);
            as.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Please select a staff ID from the list.");
        }
    }//GEN-LAST:event_admin_see_staff_buttonActionPerformed

    private void loadStaffDetails() {
        DefaultListModel<String> model = new DefaultListModel<>();
        Connection conn = null;
        Statement stmt = null;
        ResultSet rs = null;

        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital", "root", "Atoras21");
            stmt = conn.createStatement();
            rs = stmt.executeQuery("SELECT * FROM Doctor_List");

            while (rs.next()) {
                if(!rs.getString("staff_id").equals("0"))
                    model.addElement(rs.getLong("staff_id") + " " + rs.getString("doctor_first_name") + " " + rs.getString("doctor_last_name") + " " + rs.getString("doctor_title"));
            }

            admin_staff_list.setModel(model);

        } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                if (rs != null) rs.close();
                if (stmt != null) stmt.close();
                if (conn != null) conn.close();
            } catch (SQLException ex) {
                Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    private void loadPatientDetails() {
        
        Connection conn = null;
        Statement stmt = null;
        ResultSet rs = null;

        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital", "root", "Atoras21");
            stmt = conn.createStatement();
            rs = stmt.executeQuery("SELECT * FROM Doctor_Appointment_View");
            
            DefaultListModel<String> model = new DefaultListModel<>();

            while (rs.next()) {
                model.addElement(rs.getString("patient_first_name") + " got appointment from " + rs.getString("doctor_first_name"));
            }

            admin_patient_list.setModel(model);

        } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                if (rs != null) rs.close();
                if (stmt != null) stmt.close();
                if (conn != null) conn.close();
            } catch (SQLException ex) {
                Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admin_add_medicine_button;
    private javax.swing.JButton admin_add_polyclinic_button;
    private javax.swing.JButton admin_add_staff_button;
    private javax.swing.JList<String> admin_patient_list;
    private javax.swing.JScrollPane admin_patient_scroll_pane;
    private javax.swing.JButton admin_see_staff_button;
    private javax.swing.JList<String> admin_staff_list;
    private javax.swing.JScrollPane admin_staff_scroll_pane;
    private javax.swing.JButton admin_update_staff_button;
    private javax.swing.JLabel admin_welcome_back_label;
    // End of variables declaration//GEN-END:variables
}
