/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import com.mysql.cj.jdbc.Driver;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author atesz
 */
public class AdminAddMedicine extends javax.swing.JFrame {

    /**
     * Creates new form AddMedicine
     */
    public AdminAddMedicine() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add_medicine_medicine_name_label = new javax.swing.JLabel();
        add_medicine_medicine_name_textfield = new javax.swing.JTextField();
        add_medicine_n_times_label = new javax.swing.JLabel();
        add_medicine_n_times_textfield = new javax.swing.JTextField();
        add_medicine_n_days_label = new javax.swing.JLabel();
        add_medicine_n_days_textfield = new javax.swing.JTextField();
        add_medicine_approve_button = new javax.swing.JButton();
        add_medicine_cancel_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        add_medicine_medicine_name_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add_medicine_medicine_name_label.setText("Medicine Name");

        add_medicine_n_times_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add_medicine_n_times_label.setText("How Many Times in A Day?");

        add_medicine_n_days_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add_medicine_n_days_label.setText("How Many Days?");

        add_medicine_approve_button.setText("Approve");
        add_medicine_approve_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_medicine_approve_buttonActionPerformed(evt);
            }
        });

        add_medicine_cancel_button.setText("Cancel");
        add_medicine_cancel_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_medicine_cancel_buttonActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Medicine ID");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Dosage");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(add_medicine_n_days_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(add_medicine_n_times_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(add_medicine_medicine_name_label, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(add_medicine_medicine_name_textfield, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                            .addComponent(add_medicine_n_times_textfield)
                            .addComponent(add_medicine_n_days_textfield)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(add_medicine_approve_button, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addComponent(add_medicine_cancel_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jTextField1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_medicine_medicine_name_label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_medicine_medicine_name_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_medicine_n_times_label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_medicine_n_times_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_medicine_n_days_label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_medicine_n_days_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(add_medicine_approve_button, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(add_medicine_cancel_button, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void add_medicine_cancel_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_medicine_cancel_buttonActionPerformed
        this.setVisible(false);
        new Admin().setVisible(true);
    }//GEN-LAST:event_add_medicine_cancel_buttonActionPerformed

    private void add_medicine_approve_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_medicine_approve_buttonActionPerformed
        
        Connection con=null;
        PreparedStatement pt = null;
        ResultSet rs = null;
        
        try {
            
            String medication_id_s = jTextField1.getText();
            int medication_id = Integer.parseInt(medication_id_s);
            
            String Name = add_medicine_medicine_name_textfield.getText();
            
            String dosage_s = jTextField2.getText();
            int dosage = Integer.parseInt(dosage_s);
            
            String n_days_s = add_medicine_n_days_textfield.getText();
            int n_days = Integer.parseInt(n_days_s);
            
            String n_times_s = add_medicine_n_times_textfield.getText();
            int n_times = Integer.parseInt(n_times_s);
            
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital", "root","Atoras21");
            
            String sql = "INSERT INTO medicine (Medication_ID, Name, Dosage, N_days, n_times) " +
                     "VALUES (?,?,?,?,?)";
            
            pt = con.prepareStatement(sql);
            
            pt.setInt(1, medication_id);
            pt.setString(2, Name);
            pt.setInt(3, dosage);
            pt.setInt(4, n_days);
            pt.setInt(5, n_times);
            
            pt.executeUpdate();
            
            this.setVisible(false);
            new Admin().setVisible(true);
            
        } catch (SQLException ex) {
            
            JOptionPane.showMessageDialog(this, "Dosage must be between 1 and 10", "Dosage Error", JOptionPane.WARNING_MESSAGE);
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AdminAddMedicine.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Please enter valid numbers for ID, Dosage, Days, and Times", "Input Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                if (pt != null) pt.close();
                if (con != null) con.close();
            } catch (SQLException ex) {
                Logger.getLogger(AdminAddMedicine.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_add_medicine_approve_buttonActionPerformed

    public void is_ıd_exists(){
        String ıd_s = jTextField1.getText();
        
        Connection con=null;
        PreparedStatement pt = null;
        ResultSet rs = null;
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital", "root","Atoras21");
            pt = con.prepareStatement("SELECT COUNT(*) AS count FROM medicine WHERE Medication_ID =?;");
            pt.setString(1, ıd_s);
            rs = pt.executeQuery();
            
            boolean patientExists = false; // Initialize boolean variable

            if (rs.next()) {
                int count = rs.getInt("count"); // Get the value of the count column
                patientExists = count > 0; // Set patientExists to true if count > 0
            }
            if(patientExists){
                JOptionPane.showMessageDialog(this, "Medication ID is already exists.");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                // Close resources in the reverse order of their creation
                if (pt != null) {
                    pt.close();
                }
                if (con != null) {
                    con.close();
                }
            } catch (SQLException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAddMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminAddMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminAddMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminAddMedicine.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminAddMedicine().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_medicine_approve_button;
    private javax.swing.JButton add_medicine_cancel_button;
    private javax.swing.JLabel add_medicine_medicine_name_label;
    private javax.swing.JTextField add_medicine_medicine_name_textfield;
    private javax.swing.JLabel add_medicine_n_days_label;
    private javax.swing.JTextField add_medicine_n_days_textfield;
    private javax.swing.JLabel add_medicine_n_times_label;
    private javax.swing.JTextField add_medicine_n_times_textfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
