/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import com.mysql.cj.jdbc.Driver;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author atesz
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login_sign_up_button = new javax.swing.JButton();
        login_sign_in_button = new javax.swing.JButton();
        login_sign_in_ıd_textfield = new javax.swing.JTextField();
        login_sign_in_password_textfield = new javax.swing.JTextField();
        login_sign_in_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        login_sign_up_button.setText("SIGN UP");
        login_sign_up_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_sign_up_buttonActionPerformed(evt);
            }
        });

        login_sign_in_button.setText("SIGN IN");
        login_sign_in_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_sign_in_buttonActionPerformed(evt);
            }
        });

        login_sign_in_ıd_textfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        login_sign_in_ıd_textfield.setText("ID");

        login_sign_in_password_textfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        login_sign_in_password_textfield.setText("PASSWORD");

        login_sign_in_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_sign_in_label.setText("SIGN IN");
        login_sign_in_label.setPreferredSize(new java.awt.Dimension(58, 16));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(login_sign_in_label, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(login_sign_in_ıd_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(login_sign_in_password_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(login_sign_up_button, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(login_sign_in_button, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(login_sign_in_label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(login_sign_in_ıd_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(login_sign_in_password_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(login_sign_in_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(login_sign_up_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void login_sign_up_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_sign_up_buttonActionPerformed
        // add patient kısmına geçiş yapıcak
        new AddPatient().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_login_sign_up_buttonActionPerformed

    private void login_sign_in_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_sign_in_buttonActionPerformed
        Connection con=null;
        PreparedStatement pt_staff = null;
        PreparedStatement pt_patient = null;
        ResultSet rs_staff = null;
        ResultSet rs_patient = null;
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hospital", "root","Atoras21");
            pt_staff = con.prepareStatement("SELECT COUNT(*) FROM staff WHERE Staff_id =? AND password =?");
            pt_patient  = con.prepareStatement("SELECT COUNT(*) FROM patient WHERE Patient_id =? AND password =?");
            
            String sign_in_id = login_sign_in_ıd_textfield.getText();
            String sign_in_pass = login_sign_in_password_textfield.getText();
            
            pt_staff.setString(1, sign_in_id);
            pt_staff.setString(2, sign_in_pass);

            pt_patient.setString(1, sign_in_id);
            pt_patient.setString(2, sign_in_pass);

            rs_staff = pt_staff.executeQuery();
            rs_patient = pt_patient.executeQuery();
            
            rs_staff.next();
            rs_patient.next();
            int isStaff = rs_staff.getInt(1);
            int isPatient = rs_patient.getInt(1);
            
            
            if (isStaff > 0 && sign_in_id.equals("0")) {
                // staff a gidecek
                new Admin().setVisible(true);
                this.setVisible(false);
            }
            else if (isStaff > 0) {
                //admine gidecek
                Staff staff = new Staff(Long.parseLong(sign_in_id));
                staff.setVisible(true);
                this.setVisible(false);
            }
            else if (isPatient > 0) {
                //patient e gidicek
                Patient pt = new Patient(Long.parseLong(sign_in_id));
                pt.setVisible(true);
                this.setVisible(false);
            }
            
            else {
                JOptionPane.showMessageDialog(this, "Invalid User ID or Password");
            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                // Close resources in the reverse order of their creation
                if (rs_staff != null) {
                    rs_staff.close();
                }
                if (rs_patient != null) {
                    rs_patient.close();
                }
                if (pt_staff != null) {
                    pt_staff.close();
                }
                if (pt_patient != null) {
                    pt_patient.close();
                }
                if (con != null) {
                    con.close();
                }
            } catch (SQLException ex) {
                Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_login_sign_in_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton login_sign_in_button;
    private javax.swing.JLabel login_sign_in_label;
    private javax.swing.JTextField login_sign_in_password_textfield;
    private javax.swing.JTextField login_sign_in_ıd_textfield;
    private javax.swing.JButton login_sign_up_button;
    // End of variables declaration//GEN-END:variables
}
